version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tiny1
      MYSQL_DATABASE: tinyurl
      MYSQL_USER: tinyurl
      MYSQL_PASSWORD: tiny1

volumes:
  db_data: